branch-defaults:
  master:
    environment: automated-carpark-dev
    group_suffix: null
environment-defaults:
  automated-carpark-dev:
    branch: null
    repository: null
global:
  application_name: automated-carpark
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: node.js
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
